### ISSUE TITLE
dataloader.py 187 line: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by equationdz** [Tencent/TencentPretrain#42]
有没有遇到过这样的情况的? 

 LLAMA7B实在没办法了,跑不起来..用 GPT2 那个跑起来了..哎

**Comment by zjwzcnjsy** [comment]
我也遇到这个问题。
原因是llama特殊token和代码默认的不一样，这个会在预处理中引入None
解决方法：参考 https://github.com/Tencent/TencentPretrain/blob/main/documents/llama.md 中的步骤3修改特殊token字典，再进行数据的预处理，应该就可以了。
